### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by Technologx** [klinker41/evolve_theme#1]
I run into this after I import the project and let it do what it needs to.

`Error:Could not determine the class-path for interface com.android.builder.model.AndroidProject.`

**Comment by klinker24** [comment]
I have updated all the dependencies and the build. It should work fine with the latest version of Android Studio now.

**Comment by Technologx** [comment]
Thank you-------- Original Message --------Subject: Re: [klinker41/evolve_theme] Build Issue (#1)From: Luke Klinker To: klinker41/evolve_theme CC: Technologx ,Author I have updated all the dependencies and the build. It should work fine with the latest version of Android Studio now.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/klinker41/evolve_theme","title":"klinker41/evolve_theme","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/klinker41/evolve_theme"}},"updates":{"snippets":[{"icon":"PERSON","message":"@klinker24 in #1: I have updated all the dependencies and the build. It should work fine with the latest version of Android Studio now."}],"action":{"name":"View Issue","url":"https://github.com/klinker41/evolve_theme/issues/1#issuecomment-317484398"}}}

**Comment by Technologx** [comment]
I'm running into this now:

'
Information:Gradle tasks [clean, :generateDebugSources, :generateDebugAndroidTestSources, :mockableAndroidJar, :prepareDebugUnitTestDependencies, :compileDebugSources, :compileDebugAndroidTestSources, :compileDebugUnitTestSources]
Error:Some file crunching failed, see logs for details
Error:Execution failed for task ':mergeDebugResources'.
> Error: Some file crunching failed, see logs for details
Information:BUILD FAILED in 2s
Information:2 errors
'

**Comment by klinker24** [comment]
Is that after you have made changes? I am not seeing any errors on the build anymore.

**Comment by Technologx** [comment]
Yes-------- Original Message --------Subject: Re: [klinker41/evolve_theme] Build Issue (#1)From: Luke Klinker To: klinker41/evolve_theme CC: Technologx ,Author Is that after you have made changes? I am not seeing any errors on the build anymore.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/klinker41/evolve_theme","title":"klinker41/evolve_theme","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/klinker41/evolve_theme"}},"updates":{"snippets":[{"icon":"PERSON","message":"@klinker24 in #1: Is that after you have made changes? I am not seeing any errors on the build anymore."}],"action":{"name":"View Issue","url":"https://github.com/klinker41/evolve_theme/issues/1#issuecomment-317711472"}}}

**Comment by klinker24** [comment]
Ok, if it is working with a clean clone, then one of your changes made the error. I won't really be able to help with that one without seeing what you changed.

**Comment by Technologx** [comment]
I can upload to drive for you-------- Original Message --------Subject: Re: [klinker41/evolve_theme] Build Issue (#1)From: Luke Klinker To: klinker41/evolve_theme CC: Technologx ,Author Ok, if it is working with a clean clone, then one of your changes made the error. I won't really be able to help with that one without seeing what you changed.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/klinker41/evolve_theme","title":"klinker41/evolve_theme","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/klinker41/evolve_theme"}},"updates":{"snippets":[{"icon":"PERSON","message":"@klinker24 in #1: Ok, if it is working with a clean clone, then one of your changes made the error. I won't really be able to help with that one without seeing what you changed."}],"action":{"name":"View Issue","url":"https://github.com/klinker41/evolve_theme/issues/1#issuecomment-317727900"}}}

**Comment by Technologx** [comment]
I think you build tool version is wrong:

>Error:Failed to find Build Tools revision 26.0.0-rc2
<a href="install.build.tools">Install Build Tools 26.0.0-rc2 and sync project</a>

**Comment by klinker24** [comment]
No, that is fine. I updated the project to target Android O. You can download the Android O stuff from the SDK manager in Android studio.

**Comment by Technologx** [comment]
I can't download rc2 it says it's not available to download.

**Comment by klinker24** [comment]
Looks like they updated to `26.0.1` with the new release yesterday. Use that and you should be able to download it. I just did.

https://developer.android.com/preview/migration.html

**Comment by Technologx** [comment]
So I updated to that but I'm still dealing with this:

````
Information:Gradle tasks [:generateDebugSources, :generateDebugAndroidTestSources, :mockableAndroidJar, :prepareDebugUnitTestDependencies]
Error:Some file crunching failed, see logs for details
Error:Execution failed for task ':mergeDebugResources'.
> Error: Some file crunching failed, see logs for details
Information:BUILD FAILED in 8s
Information:2 errors
````

**Comment by klinker24** [comment]
If that is your custom version, something is wrong with it. You shouldn't be seeing that on the GitHub version.
